// src/icons/index.ts
import { faBuilding, faPenNib, faVideo, faBriefcase, faShirt, faBaseballBall, faMusic, faGraduationCap, faTheaterMasks, faCalendarAlt, faHatWizard, faMoneyBill, faUtensils, faFutbol, faLaugh, faGamepad, faHeartbeat, faLandmark, faHockeyPuck, faNewspaper, faInfoCircle, faStarAndCrescent, faBookOpen, faSpa, faBook, faGem, faMobileAlt, faCameraRetro, faHouseChimney, faFlask, faSchool, faBasketballBall, faComputer, faPlaneDeparture, faCar, faSuitcaseRolling } from "@fortawesome/free-solid-svg-icons";

export {
    faBuilding,
    faPenNib,
    faVideo,
    faBriefcase,
    faShirt,
    faBaseballBall,
    faMusic,
    faGraduationCap,
    faTheaterMasks,
    faCalendarAlt,
    faHatWizard,
    faMoneyBill,
    faUtensils,
    faFutbol,
    faLaugh,
    faGamepad,
    faHeartbeat,
    faLandmark,
    faHockeyPuck,
    faNewspaper,
    faInfoCircle,
    faStarAndCrescent,
    faBookOpen,
    faSpa,
    faBook,
    faGem,
    faMobileAlt,
    faCameraRetro,
    faHouseChimney,
    faFlask,
    faSchool,
    faBasketballBall,
    faComputer,
    faPlaneDeparture,
    faCar,
    faSuitcaseRolling
};
